### ISSUE TITLE
Policy: VRF-Lite 

### ISSUE THREAD

**Issue by mikewiebe** [netascode/ansible-dc-vxlan#10]
**NOTE**
We need to re-think how we support vrf-lite.  All of the information below uses the native NDFC vrf-lite functionality.  We need to discuss how we use policies directly to handle the various vrf-lite scenarios.

---------------

Role Entry Point: https://github.com/netascode/ansible-dc-vxlan/blob/main/roles/dtc/create/tasks/ndfc/main.yml#L35

The following describes the basics of NDFC VRF Lite Setup

**Topology:**

![Screenshot 2024-03-29 at 11 48 51 AM](https://github.com/netascode/ansible-dc-vxlan/assets/12445795/317f05a3-2b3b-4026-b7e3-6d09b20fb8a0)

In this sample topology we are setting up VRF Lite between the switch labeled `BW` and `external n9k`

* They are connected on interfaces (Eth1/3, Eth1/4) and (Eth1/1, Eth1/2)

**NDFC Setup:**

Two fabrics are required

* VXLAN EVPN Fabric
* External Fabric

In this case the fabric names are as follows

<img width="1354" alt="Screenshot 2024-03-29 at 11 52 52 AM" src="https://github.com/netascode/ansible-dc-vxlan/assets/12445795/c0f8a987-b6ae-446a-9ddc-f48a590ed543">

<img width="559" alt="Screenshot 2024-03-29 at 11 53 46 AM" src="https://github.com/netascode/ansible-dc-vxlan/assets/12445795/3cb8dd6e-66b2-49d4-afde-92701ed889b6">
<img width="559" alt="Screenshot 2024-03-29 at 11 53 37 AM" src="https://github.com/netascode/ansible-dc-vxlan/assets/12445795/696cd839-cd9c-4cdf-8377-f85abc5041bd">

VRF Lite Settings Under `Resources` Tab on VXLAN Fabric

<img width="843" alt="Screenshot 2024-03-29 at 11 56 31 AM" src="https://github.com/netascode/ansible-dc-vxlan/assets/12445795/9fdc115f-65b3-4d1f-862f-c24355cd8e5d">

Boarder Switch on VXLAN Fabric

<img width="1077" alt="Screenshot 2024-03-29 at 11 54 25 AM" src="https://github.com/netascode/ansible-dc-vxlan/assets/12445795/5278175a-67cf-47d8-9187-2db52b32965a">

Edge Switch on External Fabric

<img width="1134" alt="Screenshot 2024-03-29 at 11 55 32 AM" src="https://github.com/netascode/ansible-dc-vxlan/assets/12445795/f289afd8-939d-458b-8cb1-d20c658dd89c">

Link must be added for VRF Lite on External Fabric

<img width="1298" alt="Screenshot 2024-03-29 at 11 57 52 AM" src="https://github.com/netascode/ansible-dc-vxlan/assets/12445795/0d7a0255-1908-48ac-b094-fa446333a6fe">

<img width="1327" alt="Screenshot 2024-03-29 at 11 58 36 AM" src="https://github.com/netascode/ansible-dc-vxlan/assets/12445795/96699bb9-4b77-4daa-9346-36b951376cf0">

![Screenshot 2024-03-29 at 2 30 14 PM](https://github.com/netascode/ansible-dc-vxlan/assets/12445795/51be7dca-e521-496b-8f70-7fc342d516ef)

**Sample Ansible Playbook:**

```yaml
---
- hosts: netascode_rtpfabric
  any_errors_fatal: true
  gather_facts: no

  vars:
    # This testcase field can run any test in the tests directory for the role
    test_fabric: netascode_rtpfabric
    ansible_switch1: 10.122.84.55
    ansible_switch2: 10.122.84.63
    ansible_int1: Ethernet1/3
    ansible_int2: Ethernet1/4
```

```yaml
- name: VRF LITE- Create, Attach and Deploy new VRF - VLAN/VRF LITE EXTENSION Provided by the User in multiple switch
  cisco.dcnm.dcnm_vrf: &conf5
    fabric: "{{ test_fabric }}"
    state: merged
    config:
    - vrf_name: ansible-vrf-int2
      vrf_id: 9008015
      vrf_template: Default_VRF_Universal
      vrf_extension_template: Default_VRF_Extension_Universal
      vlan_id: 400
      attach:
      - ip_address: "{{ ansible_switch2 }}"
        vrf_lite:
          - peer_vrf: ansible-vrf-int1 # optional
            interface: "{{ ansible_int1 }}" # mandatory
            ipv4_addr: 10.33.0.2/24 # optional
            neighbor_ipv4: 10.33.0.1 # optional
            ipv6_addr: 2010::10:34:0:7/64 # optional
            neighbor_ipv6: 2010::10:34:0:3 # optional
            dot1q: 2 # dot1q can be got from dcnm
          - peer_vrf: ansible-vrf-int1 # optional
            interface: "{{ ansible_int2 }}" # mandatory
            ipv4_addr: 20.33.0.2/24 # optional
            neighbor_ipv4: 20.33.0.1 # optional
            ipv6_addr: 3010::10:34:0:7/64 # optional
            neighbor_ipv6: 3010::10:34:0:3 # optional
            dot1q: 21 # dot1q can be got from dcnm
      - ip_address: "{{ ansible_switch3 }}"
        vrf_lite:
          - peer_vrf: ansible-vrf-int3 # optional
            interface: "{{ ansible_int3 }}" # mandatory
            ipv4_addr: 40.33.0.2/24 # optional
            neighbor_ipv4: 40.33.0.1 # optional
            ipv6_addr: 5010::10:34:0:7/64 # optional
            neighbor_ipv6: 5010::10:34:0:3 # optional
            dot1q: 4 # dot1q can be got from dcnm
      deploy: true
  register: result
```

**NOTE:**

There is currently an issue where using the dcnm_vrf module, resources are not getting released properly

Example of resource not getting released (dot1q)

![Screenshot 2024-03-29 at 1 16 29 PM](https://github.com/netascode/ansible-dc-vxlan/assets/12445795/b7a0513d-c107-4a82-8fd1-637947456e93)

To get the list of resources the following API can be called to get the list

```
Method: GET
https://rtp-ndfc1.cisco.com/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/resource-manager/fabrics/netascode_rtpfabric
```

API to release the resource

Request URL:
https://rtp-ndfc1.cisco.com/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/resource-manager/resources?id=9805
Request Method:
DELETE

This needs to be fixed in the dcnm_vrf module ideally but could also be fixed addressed by an ansible task / action plugin
