### ISSUE TITLE
In vrf_lite, if bgp is not defined at global level, config is not rendered

### ISSUE THREAD

**Issue by GaetanoCarlucci** [netascode/ansible-dc-vxlan#234]
https://github.com/netascode/ansible-dc-vxlan/blob/d27bdec0612521342f05f56da2c8402f133f034b/roles/dtc/common/templates/ndfc_vrf_lite.j2#L4

In vrf_lite, if `bgp` is not defined at the global level but configured at the switch level, the configuration is not rendered.

For example, this config will be rendered:
```yaml
---
vxlan:
  overlay_extensions:
    vrf_lites:
      - name: bgp_vrf_lite
        vrf: NaC-VRF02
        bgp:
          graceful_restart: true
        switches:
          - name: netascode-border-2
            bgp_peers:
              - address: 10.1.2.2
                remote_as: 65010
                description: BGP Peer 1
                address_family_ipv4_unicast:
                   default_originate: true
```

but this config will not be rendered:
```yaml
---
vxlan:
  overlay_extensions:
    vrf_lites:
      - name: bgp_vrf_lite
        vrf: NaC-VRF02
        switches:
          - name: netascode-border-2
            bgp_peers:
              - address: 10.1.2.2
                remote_as: 65010
                description: BGP Peer 1
                address_family_ipv4_unicast:
                   default_originate: true
