### ISSUE TITLE
allow-as-in is created even if it is not provided

### ISSUE THREAD

**Issue by GaetanoCarlucci** [netascode/ansible-dc-vxlan#235]
https://github.com/netascode/ansible-dc-vxlan/blob/d27bdec0612521342f05f56da2c8402f133f034b/roles/dtc/common/templates/ndfc_vrf_lite_ebgp.j2#L144

allow-as-in is created even if it is not provided.

For example, if data source provided is this:
```yaml
---
vxlan:
  overlay_extensions:
    vrf_lites:
      - name: bgp_vrf_lite
        vrf: NaC-VRF02
        bgp:
          graceful_restart: true
        switches:
          - name: netascode-border-2
            bgp_peers:
              - address: 10.1.2.2
                remote_as: 65010
                description: BGP Peer 1
                address_family_ipv4_unicast:
                   default_originate: true
```

configuration rendered will contain `allow-as-in` with default value:
```
    router bgp 65002
      vrf NaC-VRF02
        router-id 10.1.2.1
        graceful-restart
        neighbor 10.1.2.2
          remote-as 65010
          description BGP Peer 1
          ebgp-multihop 2
          address-family ipv4 unicast
            allowas-in 3
            default-originate
```
