### ISSUE TITLE
Connectivity Check fails for Ansible IPv6 Host

### ISSUE THREAD

**Issue by marehler** [netascode/ansible-dc-vxlan#236]
### Ansible Version

```shell
ansible [core 2.17.0]
```

### Ansible Collection Versions

```shell
Collection                               Version
---------------------------------------- -------
ansible.netcommon                        5.3.0  
ansible.posix                            1.5.4  
ansible.utils                            2.11.0 
cisco.dcnm                               3.5.0  
cisco.nac_dc_vxlan                       0.3.0  
cisco.nxos                               5.3.0  
community.general                        8.5.0
```

### Cisco NDFC Version

```shell
12.2.2
```

### Cisco NX-OS Version

```shell
10.3(6)
```

### Which role is this issue related to?

cisco.nac_dc_vxlan.dtc.create

### Which section of the data model is this issue related to?

other

### Expected Behavior

```shell
Support for ND in IPv6-only mode.
```

### Actual Behavior

```shell
In case of an IPv6 Ansible host address, the role connectivity_check fails. Please see Steps to Reproduce below.
```

### Ansible Playbook

```yaml
# This is the main entry point playbook for calling the various roles in this collection.
- hosts: marehler_vnd3
  any_errors_fatal: true
  gather_facts: no

  roles:
    # -----------------------
    # DataCenter Roles
    #   Role: cisco.netascode_dc_vxlan.dtc manages NDFC workflows
    #
    - role: cisco.nac_dc_vxlan.dtc.create
    - role: cisco.nac_dc_vxlan.dtc.deploy
    - role: cisco.nac_dc_vxlan.dtc.remove
```

### Steps to Reproduce

```shell
Inventory with plain IPv6 host:

`
---

all:
  children:
    ndfc:
      hosts:
        marehler_vnd3:
          ansible_host: 2001:420:448b:8006::30
````

Result:

````
ansible-playbook -i inventory.yaml deploy.yaml

PLAY [marehler_vnd3] ********************************************************************************************************************************

TASK [cisco.nac_dc_vxlan.common_global : Verify User Tags] ******************************************************************************************
ok: [marehler_vnd3 -> localhost]

TASK [cisco.nac_dc_vxlan.connectivity_check : Verify Connection to NDFC 2001:420:448b:8006::30 on Port 443] *****************************************
ok: [marehler_vnd3 -> localhost]

TASK [cisco.nac_dc_vxlan.connectivity_check : Verify Authorization to NDFC 2001:420:448b:8006::30 on Port 443] **************************************
ok: [marehler_vnd3 -> localhost]

TASK [cisco.nac_dc_vxlan.connectivity_check : Get Cisco ND Version] *********************************************************************************
ok: [marehler_vnd3 -> localhost]

TASK [cisco.nac_dc_vxlan.connectivity_check : Set Cisco ND Version Var] *****************************************************************************
ok: [marehler_vnd3]

TASK [cisco.nac_dc_vxlan.connectivity_check : Get Cisco NDFC Version] *******************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was:                   reachable from the Ansible controller and try again
fatal: [marehler_vnd3]: FAILED!
<...>
Failed to parse: https://2001:420:448b:8006::30:443\n\n                  Please verify that the DCNM controller HTTPS URL (https://2001:420:448b:8006::30:443) is\n                  reachable from the Ansible controller and try again\n\n
<...>
````

Inventory with IPv6 address in square brackets:

````
---

all:
  children:
    ndfc:
      hosts:
        marehler_vnd3:
          ansible_host: "[2001:420:448b:8006::30]"
````

Result:

````
ansible-playbook -i inventory.yaml deploy.yaml

PLAY [marehler_vnd3] ********************************************************************************************************************************

TASK [cisco.nac_dc_vxlan.common_global : Verify User Tags] ******************************************************************************************
ok: [marehler_vnd3 -> localhost]

TASK [cisco.nac_dc_vxlan.connectivity_check : Verify Connection to NDFC [2001:420:448b:8006::30] on Port 443] ***************************************
fatal: [marehler_vnd3 -> localhost]: FAILED! => {"changed": false, "elapsed": 30, "msg": "Timed out waiting to connect to NDFC at https://[2001:420:448b:8006::30]:443. Check the NDFC is reachable from the Ansible Controller."}
````

Root Cause:

The cisco.dcnm.dcnm_rest module requires an IPv6 Ansible host to be enclosed in square brackets, while the ansible.builtin.wait_for module used in verify_ndfc_connectivity.yml does not support square brackets.

Proposed Fix:

Define a separate variable for the plain IPv6 address, and instruct ansible.builtin.wait_for to use that one as host if it exists.

````
---

all:
  children:
    ndfc:
      hosts:
        marehler_vnd3:
          nd_ipv6_address: 2001:420:448b:8006::30
          ansible_host: "[{{ nd_ipv6_address }}]"
````
```


### Relevant Debug Output

_No response_
