### ISSUE TITLE
TASK Build VRFs Attach List From Template fails

### ISSUE THREAD

**Issue by marehler** [netascode/ansible-dc-vxlan#237]
### Ansible Version

```shell
ansible [core 2.17.0]
```

### Ansible Collection Versions

```shell
Collection                               Version
---------------------------------------- -------
ansible.netcommon                        5.3.0  
ansible.posix                            1.5.4  
ansible.utils                            2.11.0 
cisco.dcnm                               3.5.0  
cisco.nac_dc_vxlan                       0.3.0  
cisco.nxos                               5.3.0  
community.general                        8.5.0
```

### Cisco NDFC Version

```shell
12.2.2
```

### Cisco NX-OS Version

```shell
10.3(6)
```

### Which role is this issue related to?

cisco.nac_dc_vxlan.validate

### Which section of the data model is this issue related to?

vxlan.overlay_services

### Expected Behavior

The extended service model data for the VRF attach groups should contain an 'mgmt_ip_address'.

### Actual Behavior

```shell
ansible-playbook -i inventory.yaml deploy.yaml     

PLAY [marehler_vnd3] ********************************************************************************************************************************

<...>

TASK [cisco.nac_dc_vxlan.common : Build VRFs Attach List From Template] *****************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleUndefinedVariable: 'dict object' has no attribute 'mgmt_ip_address'
fatal: [marehler_vnd3 -> localhost]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'mgmt_ip_address'"}
```

### Ansible Playbook

```yaml
---
# This is the main entry point playbook for calling the various roles in this collection.
- hosts: marehler_vnd3
  any_errors_fatal: true
  gather_facts: no

  roles:
    # -----------------------
    # DataCenter Roles
    #   Role: cisco.netascode_dc_vxlan.dtc manages NDFC workflows
    #
    - role: cisco.nac_dc_vxlan.dtc.create
    - role: cisco.nac_dc_vxlan.dtc.deploy
    - role: cisco.nac_dc_vxlan.dtc.remove
```

### Root Cause

I think the issue is caused in the Validate role in Prepare Service Model. In prep_104_fabric_overlay_services.py, for the VRF attach groups, the switch hostname is replaced with the management IP address. However, ndfc_attach_vrfs.j2 used in task Build VRFs Attach List From Template expects an 'mgmt_ip_address' variable.

````
            for switch in model_data['vxlan']['overlay_services']['vrf_attach_groups_dict'][grp['name']]:
                if any(sw['name'] == switch['hostname'] for sw in switches):
                    found_switch = next((item for item in switches if item["name"] == switch['hostname']))
                    if found_switch.get('management').get('management_ipv4_address'):
                        switch['hostname'] = found_switch['management']['management_ipv4_address']
                    elif found_switch.get('management').get('management_ipv6_address'):
                        switch['hostname'] = found_switch['management']['management_ipv6_address']
````

For the networks attach groups, such a 'mgmt_ip_address' is added instead of changing the hostname.

````
            for switch in model_data['vxlan']['overlay_services']['network_attach_groups_dict'][grp['name']]:
                if any(sw['name'] == switch['hostname'] for sw in switches):
                    found_switch = next((item for item in switches if item["name"] == switch['hostname']))
                    if found_switch.get('management').get('management_ipv4_address'):
                        switch['mgmt_ip_address'] = found_switch['management']['management_ipv4_address']
                    elif found_switch.get('management').get('management_ipv6_address'):
                        switch['mgmt_ip_address'] = found_switch['management']['management_ipv6_address']
````
