### ISSUE TITLE
TASK Add NDFC Fabric Devices <name> fails for IPv6 Devices

### ISSUE THREAD

**Issue by marehler** [netascode/ansible-dc-vxlan#251]
### Ansible Version

```shell
ansible [core 2.17.0]
```

### Ansible Collection Versions

```shell
Collection                               Version
---------------------------------------- -------
ansible.netcommon                        5.3.0  
ansible.posix                            1.5.4  
ansible.utils                            2.11.0 
cisco.dcnm                               3.5.0  
cisco.nac_dc_vxlan                       0.3.0  
cisco.nxos                               5.3.0  
community.general                        8.5.0
```

### Cisco NDFC Version

```shell
12.2.2
```

### Cisco NX-OS Version

```shell
10.3(6)
```

### Which role is this issue related to?

cisco.nac_dc_vxlan.dtc.create

### Which section of the data model is this issue related to?

vxlan.topology

### Expected Behavior

```shell
Devices with IPv6 management addresses are discovered.
```

### Actual Behavior

```shell
ansible-playbook -i inventory.yaml deploy.yaml

<...>

TASK [cisco.nac_dc_vxlan.create : Add NDFC Fabric Devices VXLAN-FABRIC-2] ***********************************************************************
task path: /Users/marehler/nac-vxlan/ansible-dc-vxlan-example/collections/ansible_collections/cisco/nac_dc_vxlan/roles/dtc/create/tasks/devices_discovery.yml:24
[WARNING]: Managing fabric switches can take a while.  Please be patient...
fatal: [marehler_vnd3]: FAILED! => {"changed": false, "module_stderr": "'int' object is not subscriptable", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error"}
```

### Ansible Playbook

```yaml
---
# This is the main entry point playbook for calling the various roles in this collection.
- hosts: marehler_vnd3
  any_errors_fatal: true
  gather_facts: no

  roles:
    # -----------------------
    # DataCenter Roles
    #   Role: cisco.netascode_dc_vxlan.dtc manages NDFC workflows
    #
    - role: cisco.nac_dc_vxlan.dtc.create
    - role: cisco.nac_dc_vxlan.dtc.deploy
    - role: cisco.nac_dc_vxlan.dtc.remove
```

### Steps to Reproduce

```shell
Use a topology with IPv6 management addresses only. Example topology_switches.yaml:

`
---
vxlan:
  topology:
    switches:
      - name: N9Kv-SPINE3
        role: spine
        serial_number: 940TOBQT4KY
        management:
          management_ipv4_address: 22.1.172.13
          default_gateway_v4: 22.1.172.1
        routing_loopback_id: 0
        interfaces:
          - name: Ethernet1/3
            mode: routed
          - name: Ethernet1/4
            mode: routed
          - name: Ethernet1/5
            mode: routed

      - name: N9Kv-LEAF3
        role: leaf
        serial_number: 9P6ZZVYAHFR
        management:
          management_ipv4_address: 22.1.172.23
          default_gateway_v4: 22.1.172.1
        routing_loopback_id: 0
        vtep_loopback_id: 1
        interfaces:
          - name: Ethernet1/2
            mode: routed
          - name: Ethernet1/3
            mode: routed
          - name: Ethernet1/4
            mode: routed
          - name: Ethernet1/5
            mode: routed

      - name: N9Kv-LEAF4
        role: leaf
        serial_number: 9IT4QPTZ8QB
        management:
          management_ipv4_address: 22.1.172.24
          default_gateway_v4: 22.1.172.1
        routing_loopback_id: 0
        vtep_loopback_id: 1
        interfaces:
          - name: Ethernet1/2
            mode: routed
          - name: Ethernet1/3
            mode: routed
          - name: Ethernet1/4
            mode: routed
          - name: Ethernet1/5
            mode: routed

    fabric_links:
      - source_device: N9Kv-SPINE3
        source_interface: eth1/1
        dest_device: N9Kv-LEAF3
        dest_interface: eth1/1
      - source_device: N9Kv-SPINE3
        source_interface: eth1/2
        dest_device: N9Kv-LEAF4
        dest_interface: eth1/1
````

This is a bug of the cisco.dcnm.dcnm_inventory module. Discovery using IPv6 management addresses works fine using via NDFC GUI as well as via API.
```


### Relevant Debug Output

_No response_
