### ISSUE TITLE
Cannot configure redistribution in BGP VRF-Lite if address-family is only under bgp_peers

### ISSUE THREAD

**Issue by ccoueffe** [netascode/ansible-dc-vxlan#252]
### Ansible Version

```shell
❯ ansible --version
ansible [core 2.17.5]
  python version = 3.11.10 (main, Sep 19 2024, 17:27:29) [Clang 16.0.0 (clang-1600.0.26.3)] 
  jinja version = 3.1.4
  libyaml = True
```

### Ansible Collection Versions

```shell
Collection         Version
------------------ -------
ansible.netcommon  5.3.0  
ansible.posix      1.5.4  
ansible.utils      2.11.0 
cisco.dcnm         3.5.1  
cisco.nac_dc_vxlan 0.3.0  
cisco.nxos         5.3.0  
community.general  8.5.0
```

### Cisco NDFC Version

```shell
12.x
```

### Which role is this issue related to?

cisco.nac_dc_vxlan.dtc.create

### Which section of the data model is this issue related to?

vxlan.overlay_extensions

### Expected Behavior

```shell
policies:
        - create_additional_policy: False
          description: nac_BGP-NaC-VRF21_vrf_lite_netascode-leaf21
          name: switch_freeform
          policy_vars:
            CONF: |-
              ! This NDFC VRF-Lite eBGP config data structure is auto-generated
              ! DO NOT EDIT MANUALLY
              !
              !
              !
              vrf context NaC-VRF21
              router bgp 65002
                vrf NaC-VRF21
                  router-id 1.1.1.2
                  bestpath as-path multipath-relax
                  graceful-restart
                  address-family ipv4 unicast
                    redistribute static route-map fabric-rmap-redist-subnet
                  neighbor 10.1.2.2
                    remote-as 65099
                    description BGP Peer 2
    [..]
```
```


### Actual Behavior

```shell
policies:
        - create_additional_policy: False
          description: nac_BGP-NaC-VRF21_vrf_lite_netascode-leaf21
          name: switch_freeform
          policy_vars:
            CONF: |-
              ! This NDFC VRF-Lite eBGP config data structure is auto-generated
              ! DO NOT EDIT MANUALLY
              !
              !
              !
              vrf context NaC-VRF21
              router bgp 65002
                vrf NaC-VRF21
                  router-id 1.1.1.2
                  bestpath as-path multipath-relax
                  graceful-restart
                  neighbor 10.1.2.2
                    remote-as 65099
                    description BGP Peer 2
                    ebgp-multihop 2
                    address-family ipv4 unicast
                      route-map rm-route-type in
                      route-map rm-route-type out
                      allowas-in 3
```
```


### Ansible Playbook

```yaml
vxlan:
  overlay_extensions:
    vrf_lites:
      - name: BGP-NaC-VRF21_vrf_lite
        vrf: NaC-VRF21
        switches:
          - name: netascode-leaf21
            router_id: 1.1.1.2
            redistribution:
              - source: static
                route_map: rm-route-static
            bgp_peers:
              - address: x.x.x.x
                remote_as: xxxxxx
                description: BGP Peer
                address_family_ipv4_unicast:
                  route_map_in: rm-route-type
                  route_map_out: rm-route-type
```

### Steps to Reproduce

```shell
N/A
```
