### ISSUE TITLE
TASK Manage NDFC Fabric VRFs fails for existing VRFs

### ISSUE THREAD

**Issue by marehler** [netascode/ansible-dc-vxlan#258]
### Ansible Version

```shell
ansible [core 2.17.0]
```

### Ansible Collection Versions

```shell
Collection                               Version
---------------------------------------- -------
ansible.netcommon                        5.3.0  
ansible.posix                            1.5.4  
ansible.utils                            2.11.0 
cisco.dcnm                               3.5.0  
cisco.nac_dc_vxlan                       0.3.0  
cisco.nxos                               5.3.0  
community.general                        8.5.0
```

### Cisco NDFC Version

```shell
12.1.3b
```

### Cisco NX-OS Version

```shell
9.3(13)
```

### Which role is this issue related to?

cisco.nac_dc_vxlan.dtc.create

### Which section of the data model is this issue related to?

vxlan.overlay_services

### Expected Behavior

```shell
Existing VRF is maintained.
```

### Actual Behavior

```shell
ansible-playbook -i inventory.yaml deploy.yaml --tags cr_manage_vrfs_networks -vvv

<...>

TASK [cisco.nac_dc_vxlan.create : Manage NDFC Fabric VRFs] ******************************************************************************************
task path: /Users/marehler/nac-vxlan/ansible-dc-vxlan-example/collections/ansible_collections/cisco/nac_dc_vxlan/roles/dtc/create/tasks/vrfs_networks.yml:35
fatal: [marehler_vnd2_1]: FAILED! => {
    "changed": false,
    "module_stderr": "invalid syntax (<unknown>, line 0)",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error"
}
```

### Ansible Playbook

```yaml
---
# This is the main entry point playbook for calling the various roles in this collection.
- hosts: marehler_vnd3
  any_errors_fatal: true
  gather_facts: no

  roles:
    # -----------------------
    # DataCenter Roles
    #   Role: cisco.netascode_dc_vxlan.dtc manages NDFC workflows
    #
    - role: cisco.nac_dc_vxlan.dtc.create
    - role: cisco.nac_dc_vxlan.dtc.deploy
    - role: cisco.nac_dc_vxlan.dtc.remove
```

### Steps to Reproduce

```shell
- Manually create and attach a VRF in NDFC
- Add the VRF with the same name, VRF ID, and VLAN to the vxlan.overlay_services.vrfs configuration data.
- Run the playbook as shown above.

Comments

- The error is caused by the cisco.dcnm.dcnm_vrf module.
- The issue does not occur if you create a new VRF.
- The issue does not occur if the existing VRF is not attached.
```

**Comment by marehler** [comment]
NDFC screenshots of sample VRF:
![NDFC-VRF-Overview](https://github.com/user-attachments/assets/e9b26ed5-e6c0-4c5f-90f2-0ce854603bf0)
![NDFC-VRF-Attachments](https://github.com/user-attachments/assets/ece2c13d-8c63-4c9b-aa5f-475465cee10f)

**Comment by marehler** [comment]
vrfs.yaml Configuration Data:
````
---
vxlan:
  overlay_services:
    vrfs:
      - name: BLUE
        vrf_id: 30001
        vlan_id: 101
        vrf_attach_group: all_leaf

    vrf_attach_groups:
      - name: all_leaf
        switches:
          - hostname: N9Kv-LEAF1
          - hostname: N9Kv-LEAF2
````

**Comment by marehler** [comment]
The issue can also be reproduced by isolating the task in a playbook and inserting the config data directly:

````
---

- name: Debug DCNM VRF
  hosts: marehler_vnd2_1
  any_errors_fatal: true
  gather_facts: no

  tasks:

  - name: Manage NDFC Fabric VRFs
    cisco.dcnm.dcnm_vrf:
      fabric: VXLAN-FABRIC-1
      state: replaced
      config:
      - vrf_name: BLUE
        vrf_id: 30001
        vlan_id: 101
        attach:
        - ip_address: 22.1.172.21
        - ip_address: 22.1.172.22
````

````
ansible-playbook -i inventory.yaml dcnm-vrf.yaml -v  
Using /Users/marehler/nac-vxlan/ansible-dc-vxlan-example/ansible.cfg as config file

PLAY [Debug DCNM VRF] *******************************************************************************************************************************

TASK [Manage NDFC Fabric VRFs] **********************************************************************************************************************
fatal: [marehler_vnd2_1]: FAILED! => {"changed": false, "module_stderr": "invalid syntax (<unknown>, line 0)", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error"}
````
