### ISSUE TITLE
Replication Mode missing in Fabric Config with IPv6 Underlay

### ISSUE THREAD

**Issue by marehler** [netascode/ansible-dc-vxlan#262]
### Ansible Version

```shell
ansible [core 2.17.0]
```

### Ansible Collection Versions

```shell
Collection                               Version
---------------------------------------- -------
ansible.netcommon                        5.3.0  
ansible.posix                            1.5.4  
ansible.utils                            2.11.0 
cisco.dcnm                               3.5.0  
cisco.nac_dc_vxlan                       0.3.0  
cisco.nxos                               5.3.0  
community.general                        8.5.0
```

### Cisco NDFC Version

```shell
12.2.2
```

### Cisco NX-OS Version

```shell
10.3(6)
```

### Which role is this issue related to?

cisco.nac_dc_vxlan.dtc.create

### Which section of the data model is this issue related to?

vxlan.underlay

### Expected Behavior

```shell
"REPLICATION_MODE": "Ingress"
```

### Actual Behavior

REPLICATION_MODE is missing in fabric config.

### Ansible Playbook

```yaml
---
# This is the main entry point playbook for calling the various roles in this collection.
- hosts: marehler_vnd3
  any_errors_fatal: true
  gather_facts: no

  roles:
    # -----------------------
    # DataCenter Roles
    #   Role: cisco.netascode_dc_vxlan.dtc manages NDFC workflows
    #
    - role: cisco.nac_dc_vxlan.dtc.create
    - role: cisco.nac_dc_vxlan.dtc.deploy
    - role: cisco.nac_dc_vxlan.dtc.remove
```

### Steps to Reproduce

```yaml
---
vxlan:
  underlay:
    general:
      enable_ipv6_underlay: true
      replication_mode: ingress
```

### RCA

In the dc_vxlan_fabric_replication.j2 template, there is a condition to include REPLICATION_MODE only if 'enable_ipv6_underlay' is false. This seems to assume that ingress replication was not supported with IPv6 underlay what is not true.

### Proposed Fix

Remove the if condition in the template.
