### ISSUE TITLE
TASK Manage Interface Routed fails for IPv6 Devices

### ISSUE THREAD

**Issue by marehler** [netascode/ansible-dc-vxlan#264]
### Ansible Version

```shell
ansible [core 2.17.0]
```

### Ansible Collection Versions

```shell
Collection                               Version
---------------------------------------- -------
ansible.netcommon                        5.3.0  
ansible.posix                            1.5.4  
ansible.utils                            2.11.0 
cisco.dcnm                               3.5.0  
cisco.nac_dc_vxlan                       0.3.0  
cisco.nxos                               5.3.0  
community.general                        8.5.0
```

### Cisco NDFC Version

```shell
12.2.2
```

### Cisco NX-OS Version

```shell
10.3(6)
```

### Which role is this issue related to?

cisco.nac_dc_vxlan.dtc.create

### Which section of the data model is this issue related to?

vxlan.topology

### Expected Behavior

```shell
Routed interfaces are configured on devices with IPv6 management addresses.
```

### Actual Behavior

```shell
TASK [cisco.nac_dc_vxlan.create : Manage Interface Routed] ******************************************************************************************
fatal: [marehler_vnd3]: FAILED! => {"changed": false, "msg": "Error: Switches ['2001:420:448b:8006:fab2:0:0:13', '2001:420:448b:8006:fab2:0:0:23', '2001:420:448b:8006:fab2:0:0:24'] are not managable in Fabric 'VXLAN-FABRIC-2', No changes are allowed on these switches\n"}
```

### Ansible Playbook

```yaml
---
# This is the main entry point playbook for calling the various roles in this collection.
- hosts: marehler_vnd3
  any_errors_fatal: true
  gather_facts: no

  roles:
    # -----------------------
    # DataCenter Roles
    #   Role: cisco.netascode_dc_vxlan.dtc manages NDFC workflows
    #
    - role: cisco.nac_dc_vxlan.dtc.create
    - role: cisco.nac_dc_vxlan.dtc.deploy
    - role: cisco.nac_dc_vxlan.dtc.remove
```

### Steps to Reproduce

```shell
Use IPv6 management addresses not using double colons. Example:

`
---
vxlan:
  topology:
    switches:
      - name: N9Kv-SPINE3
        role: spine
        serial_number: 940TOBQT4KY
        management:
          management_ipv6_address: 2001:420:448b:8006:fab2:0:0:13
          default_gateway_v6: 2001:420:448b:8006::1
        routing_loopback_id: 0
        interfaces:
          - name: Ethernet1/3
            mode: routed
            enabled: false
          - name: Ethernet1/4
            mode: routed
            enabled: false
          - name: Ethernet1/5
            mode: routed
            enabled: false
````
```


### Relevant Debug Output

_No response_
