### ISSUE TITLE
Issue with Policy for "asn", "NEIGHBOR_ASN", "BGP_AS"

### ISSUE THREAD

**Issue by juburnet** [netascode/ansible-dc-vxlan#302]
### Ansible Version

```shell
ansible [core 2.16.3]
  config file = /Users/juburnet/Library/CloudStorage/OneDrive-Cisco/Justin/SaC/sac-workspace/sac-ndfc/nac-ndfc/ansible.cfg
  configured module search path = ['/Users/juburnet/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/juburnet/.pyenv/versions/3.10.13/envs/sac-ndfc/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/juburnet/.pyenv/versions/3.10.13/envs/sac-ndfc/lib/python3.10/site-packages/ansible/collections:/Users/juburnet/Library/CloudStorage/OneDrive-Cisco/Justin/SaC/sac-workspace/sac-ndfc/nac-ndfc/collections/ansible_collections
  executable location = /Users/juburnet/.pyenv/versions/sac-ndfc/bin/ansible
  python version = 3.10.13 (main, May 10 2024, 12:56:34) [Clang 15.0.0 (clang-1500.3.9.4)] (/Users/juburnet/.pyenv/versions/3.10.13/envs/sac-ndfc/bin/python3.10)
  jinja version = 3.1.4
  libyaml = True
```

### Ansible Collection Versions

```shell
Collection         Version
------------------ -------
ansible.netcommon  7.1.0  
ansible.posix      2.0.0  
ansible.utils      5.1.2  
cisco.dcnm         3.6.0  
cisco.nac_dc_vxlan 0.4.0  
cisco.nxos         5.3.0  
community.general  10.1.0
```

### Cisco NDFC Version

```shell
Fabric Controller
Version 12.2.2.241
```

### Cisco NX-OS Version

```shell
10.3.1
```

### Which role is this issue related to?

cisco.nac_dc_vxlan.dtc.create

### Which section of the data model is this issue related to?

vxlan.policy

### Expected Behavior

```shell
For ndfc_policy.j2 template, the formatting for Policy for "asn", "NEIGHBOR_ASN", "BGP_AS"   should be the same as we have for "BGP_ASN", where quotes are required.

{% elif key == "BGP_ASN" %}
            {{ key }}: "{{ value | string | indent(12) | trim }}"
```

### Actual Behavior

```shell
We should update the ndfc_policy.j2 template and add more conditions:

New:
{% elif key in ["BGP_ASN", "asn", "NEIGHBOR_ASN", "BGP_AS"] %}
            {{ key }}: "{{ value | string | indent(12) | trim }}"
```

### Ansible Playbook

```yaml
- name: iBGP_ISN3_ISN4
        template_name: vrf_lite_ibgp
        template_vars:
          vrfName: default
          BGP_ASN: "65000.100"   <-----This currently works
          NEIGHBOR_IP: 10.65.0.10
      - name: iBGP_ISN3_ISN4_NHSelf
        template_name: bgp_neighbor_next_hop_self
        template_vars:
          vrfName: default
          BGP_NEIGHBOR: 10.65.0.10
          BGP_AS: "65000.100"   <----- needs update in jinja template
          IP_TYPE: ipv4
      - name: eBGP_ISN3_MPLS-PE
        template_name: External_VRF_Lite_eBGP
        template_vars:
          vrfName: default
          vrf_description: "To MPLS-PE1"
          asn: "65000.100"  <----- needs update in jinja template
          NEIGHBOR_ASN: "65111"  <----- needs update in jinja template
          NEIGHBOR_IP: 10.65.0.13
```

### Steps to Reproduce

Create and deploy policy with the examples above
It renders the policy without the quotes for those parameters and then it will have an error because the numbers are getting sent as float.

### Relevant Debug Output

<img width="1047" alt="Image" src="https://github.com/user-attachments/assets/67680c1f-adbd-4911-a099-8243c110cbf2" />
