### ISSUE TITLE
Add advanced fabric parameters for ISN fabric:  ENABLE_NXAPI and ENABLE_NXAPI_HTTP

### ISSUE THREAD

**Issue by juburnet** [netascode/ansible-dc-vxlan#303]
### Which role would this new feature be associated?

cisco.nac_dc_vxlan.validate

### Would this be a new feature requiring a new role?

```shell

```

### Which section of the data model is the new feature related?

vxlan.fabric

### Would this be a new feature requiring a new addition to the data model?

```shell

```

### New or Affected Documentation for New Feature

```shell

```

### Potential Ansible Task Config

```yaml
New parameters required in roles/dtc/common/templates/ndfc_fabric/isn_fabric/advanced/isn_fabric_advanced.j2


  ENABLE_NXAPI: {{ vxlan.global.enable_nxapi | default(defaults.vxlan.global.enable_nxapi) }}
  ENABLE_NXAPI_HTTP: {{ vxlan.global.enable_nxapi_http | default(defaults.vxlan.global.enable_nxapi_http ) }}
```

### Ansible Version

```shell
ansible [core 2.16.3]
  config file = /Users/juburnet/Library/CloudStorage/OneDrive-Cisco/Justin/SaC/sac-workspace/sac-ndfc/nac-ndfc/ansible.cfg
  configured module search path = ['/Users/juburnet/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/juburnet/.pyenv/versions/3.10.13/envs/sac-ndfc/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/juburnet/.pyenv/versions/3.10.13/envs/sac-ndfc/lib/python3.10/site-packages/ansible/collections:/Users/juburnet/Library/CloudStorage/OneDrive-Cisco/Justin/SaC/sac-workspace/sac-ndfc/nac-ndfc/collections/ansible_collections
  executable location = /Users/juburnet/.pyenv/versions/sac-ndfc/bin/ansible
  python version = 3.10.13 (main, May 10 2024, 12:56:34) [Clang 15.0.0 (clang-1500.3.9.4)] (/Users/juburnet/.pyenv/versions/3.10.13/envs/sac-ndfc/bin/python3.10)
  jinja version = 3.1.4
  libyaml = True
```

### Ansible Collection Versions

```shell
Collection         Version
------------------ -------
ansible.netcommon  7.1.0  
ansible.posix      2.0.0  
ansible.utils      5.1.2  
cisco.dcnm         3.6.0  
cisco.nac_dc_vxlan 0.4.0  
cisco.nxos         5.3.0  
community.general  10.1.0
```

### Cisco NDFC Version

```shell
12.2.2
```

### Cisco NX-OS Version

```shell
10.3.1
```
