### ISSUE TITLE
Range Converter Macro Does Not Work Correctly For All Range Types & Defaults

### ISSUE THREAD

**Issue by mtarking** [netascode/ansible-dc-vxlan#308]
### Ansible Version

```shell
ansible [core 2.17.8]
```

### Ansible Collection Versions

```shell
Collection         Version
------------------ -------
ansible.netcommon  7.1.0  
ansible.posix      2.0.0  
ansible.utils      5.1.2  
cisco.dcnm         3.7.0  
cisco.nac_dc_vxlan 0.4.0  
cisco.nxos         9.2.1  
community.general  10.1.0
```

### Cisco NDFC Version

```shell
12.2.2
```

### Cisco NX-OS Version

```shell

```

### Which role is this issue related to?

cisco.nac_dc_vxlan.dtc.create

### Which section of the data model is this issue related to?

vxlan.fabric

### Expected Behavior

```shell
Expected ranger converter macro to handle the different ranges types used.
```

### Actual Behavior

```shell

```

### Ansible Playbook

```yaml
---
# This is the main entry point playbook for calling the various
# roles in this collection.
- hosts: nac-fabric1
  # connection: local
  any_errors_fatal: true
  gather_facts: no

  roles:
    - role: cisco.nac_dc_vxlan.dtc.create
      tags: 'role_create'
```

### Steps to Reproduce

```shell
Configure spanning-tree but rely solely on defaults for the VLAN range.
```

### Relevant Debug Output

```shell

```
