### ISSUE TITLE
VRF-Lite policy creates multiple copies of policy vs checking to see if it exists

### ISSUE THREAD

**Issue by carschmi** [netascode/ansible-dc-vxlan#314]
### Ansible Version

```shell
2.17
```

### Ansible Collection Versions

```shell
root@52a4fc410e40:/#  ansible-galaxy collection list
/root/.ansible/collections/ansible_collections
Collection         Version
ansible.netcommon  7.1.0
ansible.posix      2.0.0
ansible.utils      5.1.2
cisco.dcnm         3.7.0
cisco.nac_dc_vxlan 0.4.0
community.general  10.1.0
```

### Cisco NDFC Version

```shell
Fabric Controller
Version 12.2.2.241
```

### Cisco NX-OS Version

```shell
10.4.4m
```

### Which role is this issue related to?

cisco.nac_dc_vxlan.dtc.create

### Which section of the data model is this issue related to?

vxlan.overlay_extension

### Expected Behavior

```shell
NAC checks if the vrf-lite freeform exists and only creates it if it doesn't
```

### Actual Behavior

```shell
NAC creates the vrf-lite freeform every time the pipeline funs
```

### Ansible Playbook

```yaml
---
vxlan:
  overlay_extensions:
    vrf_lites:
      - name: Default-VRF-L3Out #(NDi connectivity via default vrf)
        vrf: default
        ospf:
          process: UNDERLAY
          areas:
            - id: 0
              area_type: standard
          bfd:
            enabled: true
        switches:
          - name: Leaf-1
            interfaces:
              - name: ethernet1/53.11
                ospf:
                  area: 0.0.0.0
                  passive_interface: false
                  network_type: point-to-point
                  bfd:
                    enabled: false
          - name: Leaf-2
            interfaces:
              - name: ethernet1/53.11
                ospf:
                  area: 0.0.0.0
                  passive_interface: false
                  network_type: point-to-point
                  bfd:
                    enabled: false


      - name: Scout-vrf1-Core-1 #(L3out for Tenant VRF)
        vrf: Scout-vrf1
        bgp:
        switches:
          - name: Leaf-1
            router_id: 198.19.1.251
            bgp:
              best_path_as_path_relax: true
              local_as: 65001
              address_family_ipv4_unicast:
                  send_community: true
                  send_ext_community: true
            bgp_peers:
              - address: 198.19.1.4
                remote_as: 65000
                description: Scout-vrf1 Core-1 BGP session
                ebgp_multihop: 5
                update_source: e1/53.10
                address_family_ipv4_unicast:
                  send_community: true
                  send_ext_community: true
          - name: Leaf-2
            router_id: 198.19.1.252
            bgp:
              best_path_as_path_relax: true
              local_as: 65001
              address_family_ipv4_unicast:
                  send_community: true
                  send_ext_community: true
            bgp_peers:
              - address: 198.19.1.6
                remote_as: 65000
                description: Core-1 nodes
                ebgp_multihop: 5
                update_source: e1/53.10
                address_family_ipv4_unicast:
                  send_community: true
                  send_ext_community: true



      - name: Scout-vrf2-Core-1 #(Test L3Out)
        vrf: Scout-vrf2
        bgp:
        switches:
          - name: Leaf-1
            router_id: 198.19.1.241
            bgp:
              best_path_as_path_relax: true
              local_as: 65001
              address_family_ipv4_unicast:
            bgp_peers:
              - address: 198.19.1.12
                remote_as: 65000
                description: Core-1 nodes
                ebgp_multihop: 5
                update_source: e1/53.12
                address_family_ipv4_unicast:
                  send_community: true
                  send_ext_community: true
```

### Steps to Reproduce

```shell
---
vxlan:
  overlay_extensions:
    vrf_lites:
      - name: Default-VRF-L3Out #(NDi connectivity via default vrf)
        vrf: default
        ospf:
          process: UNDERLAY
          areas:
            - id: 0
              area_type: standard
          bfd:
            enabled: true
        switches:
          - name: Leaf-1
            interfaces:
              - name: ethernet1/53.11
                ospf:
                  area: 0.0.0.0
                  passive_interface: false
                  network_type: point-to-point
                  bfd:
                    enabled: false
          - name: Leaf-2
            interfaces:
              - name: ethernet1/53.11
                ospf:
                  area: 0.0.0.0
                  passive_interface: false
                  network_type: point-to-point
                  bfd:
                    enabled: false


      - name: Scout-vrf1-Core-1 #(L3out for Tenant VRF)
        vrf: Scout-vrf1
        bgp:
        switches:
          - name: Leaf-1
            router_id: 198.19.1.251
            bgp:
              best_path_as_path_relax: true
              local_as: 65001
              address_family_ipv4_unicast:
                  send_community: true
                  send_ext_community: true
            bgp_peers:
              - address: 198.19.1.4
                remote_as: 65000
                description: Scout-vrf1 Core-1 BGP session
                ebgp_multihop: 5
                update_source: e1/53.10
                address_family_ipv4_unicast:
                  send_community: true
                  send_ext_community: true
          - name: Leaf-2
            router_id: 198.19.1.252
            bgp:
              best_path_as_path_relax: true
              local_as: 65001
              address_family_ipv4_unicast:
                  send_community: true
                  send_ext_community: true
            bgp_peers:
              - address: 198.19.1.6
                remote_as: 65000
                description: Core-1 nodes
                ebgp_multihop: 5
                update_source: e1/53.10
                address_family_ipv4_unicast:
                  send_community: true
                  send_ext_community: true



      - name: Scout-vrf2-Core-1 #(Test L3Out)
        vrf: Scout-vrf2
        bgp:
        switches:
          - name: Leaf-1
            router_id: 198.19.1.241
            bgp:
              best_path_as_path_relax: true
              local_as: 65001
              address_family_ipv4_unicast:
            bgp_peers:
              - address: 198.19.1.12
                remote_as: 65000
                description: Core-1 nodes
                ebgp_multihop: 5
                update_source: e1/53.12
                address_family_ipv4_unicast:
                  send_community: true
                  send_ext_community: true
```

### Relevant Debug Output

```shell
reach out to carschmi or mtarking for more detail if needed
```
