### ISSUE TITLE
TASK Build Fabric Links fails in 0.4.0

### ISSUE THREAD

**Issue by marehler** [netascode/ansible-dc-vxlan#336]
### Ansible Version

```shell
ansible [core 2.17.0]
```

### Ansible Collection Versions

```shell
Collection                               Version
---------------------------------------- -------
ansible.netcommon                        7.1.0  
ansible.posix                            2.0.0  
ansible.utils                            5.1.2  
cisco.dcnm                               3.7.0  
cisco.nac_dc_vxlan                       0.4.0  
cisco.nxos                               9.4.0  
community.general                        10.5.0
```

### Cisco NDFC Version

```shell
12.2.2
```

### Cisco NX-OS Version

```shell
10.3(6)
```

### Which role is this issue related to?

cisco.nac_dc_vxlan.dtc.create

### Which section of the data model is this issue related to?

vxlan.topology

### Expected Behavior

```shell
Fabric links should be built without optional attributes.
```

### Actual Behavior

The task fails with release 0.4.0. It works with release 0.3.0.

```
TASK [cisco.nac_dc_vxlan.common : Build Fabric Links] ***********************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleUndefinedVariable: 'dict object' has no attribute 'admin_state'
fatal: [marehler_vnd3 -> localhost]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'admin_state'"}
```

### Ansible Playbook

```yaml
---
# This is the main entry point playbook for calling the various roles in this collection.

- hosts: marehler_vnd3
  any_errors_fatal: true
  gather_facts: no

  roles:
    # -----------------------
    # DataCenter Roles
    #   Role: cisco.netascode_dc_vxlan.dtc manages NDFC workflows
    #
    - role: cisco.nac_dc_vxlan.dtc.create
    - role: cisco.nac_dc_vxlan.dtc.deploy
    - role: cisco.nac_dc_vxlan.dtc.remove
```

### Steps to Reproduce

Run playbook for the following topology configuration.

```
---
vxlan:
  topology:
    switches:
      - name: N9Kv-SPINE3
        role: spine
        serial_number: 940TOBQT4KY
        management:
          management_ipv6_address: 2001:420:448b:8006:fab2::13
          default_gateway_v6: 2001:420:448b:8006::1
        routing_loopback_id: 0
        interfaces:
          - name: Ethernet1/3
            mode: routed
            enabled: false
          - name: Ethernet1/4
            mode: routed
            enabled: false
          - name: Ethernet1/5
            mode: routed
            enabled: false

      - name: N9Kv-LEAF3
        role: leaf
        serial_number: 9P6ZZVYAHFR
        management:
          management_ipv6_address: 2001:420:448b:8006:fab2::23
          default_gateway_v6: 2001:420:448b:8006::1
        routing_loopback_id: 0
        vtep_loopback_id: 1
        interfaces:
          - name: Ethernet1/2
            mode: routed
            enabled: false
          - name: Ethernet1/3
            mode: routed
            enabled: false
          - name: Ethernet1/4
            mode: routed
            enabled: false
          - name: Ethernet1/5
            mode: routed
            enabled: false

      - name: N9Kv-LEAF4
        role: leaf
        serial_number: 9IT4QPTZ8QB
        management:
          management_ipv6_address: 2001:420:448b:8006:fab2::24
          default_gateway_v6: 2001:420:448b:8006::1
        routing_loopback_id: 0
        vtep_loopback_id: 1
        interfaces:
          - name: Ethernet1/2
            mode: routed
            enabled: false
          - name: Ethernet1/3
            mode: routed
            enabled: false
          - name: Ethernet1/4
            mode: routed
            enabled: false
          - name: Ethernet1/5
            mode: routed
            enabled: false

    fabric_links:
      - source_device: N9Kv-SPINE3
        source_interface: eth1/1
        dest_device: N9Kv-LEAF3
        dest_interface: eth1/1
        template: int_intra_fabric_ipv6_link_local
      - source_device: N9Kv-SPINE3
        source_interface: eth1/2
        dest_device: N9Kv-LEAF4
        dest_interface: eth1/1
        template: int_intra_fabric_ipv6_link_local
```

### Root Cause Analysis:

The 'admin_state', 'mtu', 'source_description', and 'destination_description' attributes are optional, however in the 'ndfc_fabric_links.j2' template they are required:

```
---
# This NDFC fabric links config data structure is auto-generated
# DO NOT EDIT MANUALLY
#
{% for link in MD_Extended.vxlan.topology.fabric_links %}
  - dst_fabric: "{{ MD_Extended.vxlan.fabric.name }}"
    src_interface: "{{ link.source_interface }}"
    dst_interface: "{{ link.dest_interface }}"
    src_device: "{{ link.source_device }}"
    dst_device: "{{ link.dest_device }}"
    template: "{{ link.template }}"
    profile:
        admin_state: "{{ link.admin_state }}"
        mtu: "{{ link.mtu }}"
        peer1_description: "{{ link.source_description | default('') }}"
        peer2_description: "{{ link.destination_description | default('') }}"
{% endfor %}
```
