### ISSUE TITLE
TASK Manage NDFC Fabric Links fails in 0.4.0

### ISSUE THREAD

**Issue by marehler** [netascode/ansible-dc-vxlan#340]
### Ansible Version

```shell
ansible [core 2.17.0]
```

### Ansible Collection Versions

```shell
Collection                               Version
---------------------------------------- -------
ansible.netcommon                        7.1.0  
ansible.posix                            2.0.0  
ansible.utils                            5.1.2  
cisco.dcnm                               3.7.0  
cisco.nac_dc_vxlan                       0.4.0  
cisco.nxos                               9.4.0  
community.general                        10.5.0
```

### Cisco NDFC Version

```shell
12.2.2
```

### Cisco NX-OS Version

```shell
10.3(6)
```

### Which role is this issue related to?

cisco.nac_dc_vxlan.dtc.create

### Which section of the data model is this issue related to?

vxlan.topology

### Expected Behavior

Fabric links should be created.

### Actual Behavior

The task fails with release 0.4.0. It worked with release 0.3.0.

```
TASK [cisco.nac_dc_vxlan.create : Manage NDFC Fabric Links] *****************************************************************************************
fatal: [marehler_vnd3]: FAILED! => {"changed": false, "msg": "{\"Error\": \"Given switch elem = \\\"N9Kv-LEAF3\\\" is not a valid one for this fabric\\n\"}"}
```

The error message is incorrect. The switch element is valid and exists. The input to the step looks correct too.

### Ansible Playbook

```yaml
---
# This is the main entry point playbook for calling the various roles in this collection.

- hosts: marehler_vnd3
  any_errors_fatal: true
  gather_facts: no

  roles:
    # -----------------------
    # DataCenter Roles
    #   Role: cisco.netascode_dc_vxlan.dtc manages NDFC workflows
    #
    - role: cisco.nac_dc_vxlan.dtc.create
    - role: cisco.nac_dc_vxlan.dtc.deploy
    - role: cisco.nac_dc_vxlan.dtc.remove
```

### Steps to Reproduce

Run playbook for the following topology configuration.

```
---
vxlan:
  topology:
    switches:
      - name: N9Kv-SPINE3
        role: spine
        serial_number: 940TOBQT4KY
        management:
          management_ipv6_address: 2001:420:448b:8006:fab2::13
          default_gateway_v6: 2001:420:448b:8006::1
        routing_loopback_id: 0
        interfaces:
          - name: Ethernet1/3
            mode: routed
            enabled: false
          - name: Ethernet1/4
            mode: routed
            enabled: false
          - name: Ethernet1/5
            mode: routed
            enabled: false

      - name: N9Kv-LEAF3
        role: leaf
        serial_number: 9P6ZZVYAHFR
        management:
          management_ipv6_address: 2001:420:448b:8006:fab2::23
          default_gateway_v6: 2001:420:448b:8006::1
        routing_loopback_id: 0
        vtep_loopback_id: 1
        interfaces:
          - name: Ethernet1/2
            mode: routed
            enabled: false
          - name: Ethernet1/3
            mode: routed
            enabled: false
          - name: Ethernet1/4
            mode: routed
            enabled: false
          - name: Ethernet1/5
            mode: routed
            enabled: false

      - name: N9Kv-LEAF4
        role: leaf
        serial_number: 9IT4QPTZ8QB
        management:
          management_ipv6_address: 2001:420:448b:8006:fab2::24
          default_gateway_v6: 2001:420:448b:8006::1
        routing_loopback_id: 0
        vtep_loopback_id: 1
        interfaces:
          - name: Ethernet1/2
            mode: routed
            enabled: false
          - name: Ethernet1/3
            mode: routed
            enabled: false
          - name: Ethernet1/4
            mode: routed
            enabled: false
          - name: Ethernet1/5
            mode: routed
            enabled: false

    fabric_links:
      - source_device: N9Kv-SPINE3
        source_interface: eth1/1
        dest_device: N9Kv-LEAF3
        dest_interface: eth1/1
        template: int_intra_fabric_ipv6_link_local
      - source_device: N9Kv-SPINE3
        source_interface: eth1/2
        dest_device: N9Kv-LEAF4
        dest_interface: eth1/1
        template: int_intra_fabric_ipv6_link_local
```

### Relevant Debug Output

```shell
TASK [cisco.nac_dc_vxlan.create : Debug Manage NDFC Fabric Links - MD_Extended.vxlan.fabric.name] ***************************************************
ok: [marehler_vnd3] => {
    "msg": "VXLAN-FABRIC-2"
}

TASK [cisco.nac_dc_vxlan.create : Debug Manage NDFC Fabric Links - required_links] ******************************************************************
ok: [marehler_vnd3] => {
    "msg": [
        {
            "dst_device": "N9Kv-LEAF3",
            "dst_fabric": "VXLAN-FABRIC-2",
            "dst_interface": "eth1/1",
            "src_device": "N9Kv-SPINE3",
            "src_interface": "eth1/1",
            "template": "int_intra_fabric_ipv6_link_local"
        },
        {
            "dst_device": "N9Kv-LEAF4",
            "dst_fabric": "VXLAN-FABRIC-2",
            "dst_interface": "eth1/1",
            "src_device": "N9Kv-SPINE3",
            "src_interface": "eth1/2",
            "template": "int_intra_fabric_ipv6_link_local"
        }
    ]
}

TASK [cisco.nac_dc_vxlan.create : Manage NDFC Fabric Links] *****************************************************************************************
fatal: [marehler_vnd3]: FAILED! => {"changed": false, "msg": "{\"Error\": \"Given switch elem = \\\"N9Kv-LEAF3\\\" is not a valid one for this fabric\\n\"}"}
```

**Comment by marehler** [comment]
I can reproduce the issue using the dcnm_links module:

````
---

- name: Debug fabric link creation
  hosts: marehler_vnd3
  any_errors_fatal: true
  gather_facts: no

  tasks:

  - name: Manage NDFC Fabric Links
    cisco.dcnm.dcnm_links:
      src_fabric: VXLAN-FABRIC-2
      config:
        - dst_device: "N9Kv-LEAF3"
          dst_fabric: "VXLAN-FABRIC-2"
          dst_interface: "eth1/1"
          src_device: "N9Kv-SPINE3"
          src_interface: "eth1/1"
          template: "int_intra_fabric_ipv6_link_local"
        - dst_device: "N9Kv-LEAF4"
          dst_fabric: "VXLAN-FABRIC-2"
          dst_interface: "eth1/1"
          src_device: "N9Kv-SPINE3"
          src_interface: "eth1/2"
          template: "int_intra_fabric_ipv6_link_local"
      deploy: false
      state: merged
    register: manage_fabric_links_result
````

Result:

````
TASK [Manage NDFC Fabric Links] *********************************************************************************************************************
fatal: [marehler_vnd3]: FAILED! => {"changed": false, "msg": "{\"Error\": \"Given switch elem = \\\"N9Kv-LEAF3\\\" is not a valid one for this fabric\\n\"}"}
````

Apparently the dcnm_links module cannot handle device names instead of IP addresses. Not sure if this is a bug in the module, or if NaC VXLAN should pass IP addresses to the module.

In addition, port profile parameters are mandatory which are optional in the NaC VXLAN data model. This is related to issue #336.

The following playbook works:

````
---

- name: Debug fabric link creation
  hosts: marehler_vnd3
  any_errors_fatal: true
  gather_facts: no

  tasks:

  - name: Manage NDFC Fabric Links
    cisco.dcnm.dcnm_links:
      src_fabric: VXLAN-FABRIC-2
      config:
        - dst_device: "2001:420:448b:8006:fab2::23"
          dst_fabric: "VXLAN-FABRIC-2"
          dst_interface: "eth1/1"
          src_device: "2001:420:448b:8006:fab2::13"
          src_interface: "eth1/1"
          template: "int_intra_fabric_ipv6_link_local"
          profile:
            admin_state: true
            mtu: 9216
        - dst_device: "2001:420:448b:8006:fab2::24"
          dst_fabric: "VXLAN-FABRIC-2"
          dst_interface: "eth1/1"
          src_device: "2001:420:448b:8006:fab2::13"
          src_interface: "eth1/2"
          template: "int_intra_fabric_ipv6_link_local"
          profile:
            admin_state: true
            mtu: 9216
      deploy: false
      state: merged
    register: manage_fabric_links_result
````

Result:

````
TASK [Manage NDFC Fabric Links] *********************************************************************************************************************
changed: [marehler_vnd3] => {"changed": true, "response": [{"DATA": {"linkUUID": "LINK-UUID-396000", "status": "Success"}, "MESSAGE": "OK", "METHOD": "POST", "REQUEST_PATH": "https://[2001:420:448b:8006::30]:443/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/links", "RETURN_CODE": 200}, {"DATA": {"linkUUID": "LINK-UUID-396010", "status": "Success"}, "MESSAGE": "OK", "METHOD": "POST", "REQUEST_PATH": "https://[2001:420:448b:8006::30]:443/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/links", "RETURN_CODE": 200}]}
````
