### ISSUE TITLE
Banner missing new line

### ISSUE THREAD

**Issue by ccoueffe** [netascode/ansible-dc-vxlan#343]
### Ansible Version

```shell
ansible [core 2.16.3]
  config file = /home/gitlab-runner/builds/a6Y9Wv_tx/0/ccoueffe/ndfc-ansbile-as-code/nac-ndfc/ansible.cfg
  configured module search path = ['/home/gitlab-runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/gitlab-runner/.pyenv/versions/3.10.15/envs/sac-ndfc/lib/python3.10/site-packages/ansible
  ansible collection location = /home/gitlab-runner/builds/a6Y9Wv_tx/0/ccoueffe/ndfc-ansbile-as-code/nac-ndfc/collections/ansible_collections
  executable location = /home/gitlab-runner/.pyenv/versions/sac-ndfc/bin/ansible
  python version = 3.10.15 (main, Nov  5 2024, 18:23:18) [GCC 12.2.0] (/home/gitlab-runner/.pyenv/versions/3.10.15/envs/sac-ndfc/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

### Ansible Collection Versions

```shell
# /home/gitlab-runner/builds/a6Y9Wv_tx/0/ccoueffe/ndfc-ansbile-as-code/nac-ndfc/collections/ansible_collections
Collection         Version
------------------ -------
ansible.netcommon  7.1.0  
ansible.posix      2.0.0  
ansible.utils      5.1.2  
cisco.dcnm         3.7.0  
cisco.nac_dc_vxlan 0.4.0  
community.general  10.1.0
```

### Cisco NDFC Version

```shell
12.2
```

### Cisco NX-OS Version

```shell

```

### Which role is this issue related to?

cisco.nac_dc_vxlan.dtc.create

### Which section of the data model is this issue related to?

vxlan.policy

### Expected Behavior

```shell
Should allow the new line at the end of the banner to avoid overlap with system prompt.

Bug is present in single and multilines.

Ex:

> ssh admin@10.229.42.82
***************************************************************************
*               Vxlan as Code demo - fabric EVPN nac-ndfc3                *
***************************************************************************
Password:
```

### Actual Behavior

```shell
Last new line is removed.

> ssh admin@10.229.42.82
***************************************************************************
*               Vxlan as Code demo - fabric EVPN nac-ndfc3                *
Password: *****************************************************************
```

### Ansible Playbook

```yaml
Data source:


      - name: banner_new
        template_name: banner
        template_vars:
          BANNER: |-
            ***************************************************************************
            *               Vxlan as Code demo - fabric EVPN nac-ndfc3                *
            ***************************************************************************
          BANNERDELIMITER: "_"
          TYPE: "motd"
```

### Steps to Reproduce

```shell
NA
```

### Relevant Debug Output

```shell

```
