### ISSUE TITLE
Create Networks Issue when Interface policy is not correct

### ISSUE THREAD

**Issue by mikewiebe** [netascode/ansible-dc-vxlan#35]
Found an issue today testing creation of networks.  Consider the following example

```yaml
---
fabric:
  overlay_services:
    networks:
      - name: NetAsCodeNet1
        vrf_name: NetAsCodeVrf1
        net_id: 130001
        vlan_id: 2301
        vlan_name: NetAsCodeNet1_vlan2301
        gw_ip_address: "192.168.12.1/24"
        attach_group: all_leaf

    network_attach_groups:
      - name: all_leaf
        switches:
          - {hostname: 10.122.84.55, ports: [Ethernet1/13, Ethernet1/14]}
          - {hostname: 10.122.84.56, ports: [Ethernet1/13, Ethernet1/14]}
```

If `Ethernet1/13 and 1/14` in this example are using the wrong policy creating these networks will fail with the following error

```
   "msg": {
        "DATA": {
            "NetAsCodeNet1-[9Q79VH3E4J4/netascode-rtp-leaf2]": "Invalid Interfaces in netascode-rtp-leaf2. Invalid interfaces are Ethernet1/13,Ethernet1/14.",
```

In this case the interfaces needed to be trunk interfaces but they were routed.

We need to account for this in the workflow since the interface configure section comes after the network creation section currently.

Need to check and see if we can move the interface management tasks before network/vrf management tasks
