### ISSUE TITLE
MSD Task "Build VRFs Attach List From Template" fails when using Tags

### ISSUE THREAD

**Issue by marehler** [netascode/ansible-dc-vxlan#380]
### Ansible Version

```shell
ansible [core 2.16.3]
```

### Ansible Collection Versions

```shell
Collection                               Version
---------------------------------------- -------
ansible.netcommon                        7.1.0  
ansible.posix                            2.0.0  
ansible.utils                            5.1.2  
cisco.dcnm                               3.7.0  
cisco.nac_dc_vxlan                       0.4.1  
cisco.nxos                               9.4.0  
community.general                        10.1.0
```

### Cisco NDFC Version

```shell
12.2.3
```

### Cisco NX-OS Version

```shell
10.5(3)
```

### Which role is this issue related to?

cisco.nac_dc_vxlan.dtc.create

### Which section of the data model is this issue related to?

vxlan.multisite

### Expected Behavior

The task should succeed.

### Actual Behavior

```shell
TASK [cisco.nac_dc_vxlan.create : Build VRFs Attach List From Template] **************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleUndefinedVariable: 'vrf_attach_groups_dict' is undefined. 'vrf_attach_groups_dict' is undefined
fatal: [blndc01-cx-nd -> localhost]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'vrf_attach_groups_dict' is undefined. 'vrf_attach_groups_dict' is undefined"}"
```

### Ansible Playbook

```yaml
# This is the main entry point playbook for calling the various roles in this collection.

- hosts: blndc01-cx-nd
  any_errors_fatal: true
  gather_facts: no

  roles:
    # -----------------------
    # DataCenter Roles
    #   Role: cisco.netascode_dc_vxlan.dtc manages NDFC workflows
    #
    - role: cisco.nac_dc_vxlan.dtc.create
    - role: cisco.nac_dc_vxlan.dtc.deploy
    - role: cisco.nac_dc_vxlan.dtc.remove
```

### Steps to Reproduce

```shell
export ANSIBLE_RUN_TAGS='cr_manage_vrfs_networks,role_deploy'
ansible-playbook -i inventory.yaml deploy.yaml
```

### Relevant Debug Output

```shell

```

### Analysis

In 'sub_main_msd.yaml, task "Prepare Multisite Data" is skipped, and variable MD_Multisite is undefined. This task seems to miss some tags.
