### ISSUE TITLE
Syntax Warnings "invalid escape sequence \d" when using Python 3.12

### ISSUE THREAD

**Issue by marehler** [netascode/ansible-dc-vxlan#390]
### Ansible Version

```shell
ansible [core 2.16.3]
```

### Ansible Collection Versions

```shell
Collection         Version
------------------ -------
ansible.netcommon  7.1.0  
ansible.posix      2.0.0  
ansible.utils      5.1.2  
cisco.dcnm         3.7.0  
cisco.nac_dc_vxlan 0.4.1  
cisco.nxos         5.3.0  
community.general  10.1.0
```

### Cisco NDFC Version

```shell
12.2.3
```

### Cisco NX-OS Version

```shell
10.5(3)
```

### Which role is this issue related to?

cisco.nac_dc_vxlan.validate

### Which section of the data model is this issue related to?

other

### Expected Behavior

```shell
TASK [cisco.nac_dc_vxlan.validate : Perform Required Syntax and Semantic Model Validation] **********************************************************
ok: [blndc01-cx-nd -> localhost]

TASK [cisco.nac_dc_vxlan.validate : Perform Custom Enhanced Syntax and Semantic Model Validation] ***************************************************
ok: [blndc01-cx-nd -> localhost]
```

### Actual Behavior

```shell
TASK [cisco.nac_dc_vxlan.validate : Perform Required Syntax and Semantic Model Validation] **********************************************************
<unknown>:4: SyntaxWarning: invalid escape sequence '\d'
<unknown>:5: SyntaxWarning: invalid escape sequence '\d'
<unknown>:5: SyntaxWarning: invalid escape sequence '\d'
ok: [blndc01-cx-nd -> localhost]

TASK [cisco.nac_dc_vxlan.validate : Perform Custom Enhanced Syntax and Semantic Model Validation] ***************************************************
<unknown>:4: SyntaxWarning: invalid escape sequence '\d'
<unknown>:5: SyntaxWarning: invalid escape sequence '\d'
<unknown>:5: SyntaxWarning: invalid escape sequence '\d'
ok: [blndc01-cx-nd -> localhost]
```

### Ansible Playbook

```yaml
---
# Playbook including validate role only

- hosts: blndc01-cx-nd
  any_errors_fatal: true
  gather_facts: no

  roles:
    # Prepare service model for all subsequent roles
    #
    - role: cisco.nac_dc_vxlan.validate
```

### Steps to Reproduce

```shell
python --version
Python 3.12.3
ansible-playbook -i inventory.yaml validate.yaml
```

### Relevant Debug Output

```shell

```
