### ISSUE TITLE
Role: cisco.nac_dc_vxlan.dtc.create - vPC Peering

### ISSUE THREAD

**Issue by mikewiebe** [netascode/ansible-dc-vxlan#4]
Role Entry Point: https://github.com/netascode/ansible-dc-vxlan/blob/main/roles/dtc/create/tasks/ndfc/main.yml#L23

Role should make use of the following NDFC Ansible Collection [dcnm_vpc_pair](https://github.com/CiscoDevNet/ansible-dcnm/pull/273)
  * Note, this module is still in development but close to completion so we can start to integrate with it.
  * Example Module Call: https://github.com/CiscoDevNet/ansible-dcnm/pull/273/files#diff-648aece2b9e02438618cd89a66dbf4f287abb3c167b8b4592657bc259b7bf680R30

This work item should enable creation of a vPC peer between two leaf devices:

**Scope of Work:**
* Build out Jinja2 Template to pass payload to module
    * Entry point for jinja2 file creation.  Include task file here to create template and template data
    * https://github.com/netascode/ansible-dc-vxlan/blob/main/roles/dtc/common/tasks/main.yml
* Action plugin if needed to transform data into more useable format

GUI Example for creating vPC pair (https://ndfc-lab.ciscolive.com/lab/pod1/ndfc-fabric1/vpc)

Relavant Schema:
* https://wwwin-github.cisco.com/netascode/nac-dc-vxlan/blob/master/schemas/fabric_schema.yaml#L28
* https://wwwin-github.cisco.com/netascode/nac-dc-vxlan/blob/master/schemas/fabric_schema.yaml#L45

Sample Service Model Data:

```yaml
fabric:
  global:
    vpc:
      peer_link_vlan: 3600
      peer_keep_alive: management
      auto_recovery_time: 240
      delay_restore_time: 150
      peer_link_port_channel_id: 500
      advertise_pip: False
      advertise_pip_border_only: True
      domain_id_range: 1-100
```

```yaml
fabric:
  topology:
    vpc_peers:
      - peer1: netascode-leaf1
        peer1_peerlink_interfaces:
          - name: eth1/3
          - name: eth1/4
        peer2: netascode-leaf2
        peer2_peerlink_interfaces:
          - name: eth1/3
          - name: eth1/4
        fabric_peering: false
        domain_id: 10
        vtep_vip: "10.10.88.1"
        vpc_interfaces:
          - vpc_id: 10
```

Sample task to query vPC peer status data

```yaml
- debug: msg="{{ item.peer1 }}, {{ item.peer2 }}"
  loop: "{{ MD.fabric.topology.vpc_peers }}"


- name: Query Fabric {{ MD.fabric.name }} Peers for VPC Configuration
  cisco.dcnm.dcnm_inventory:
    fabric: "{{ MD.fabric.name }}"
    state: query
    config:
      - seed_ip: "{{ MD.fabric.topology.leaf[item.peer1].management_ipv4_address }}"
      - seed_ip: "{{ MD.fabric.topology.leaf[item.peer2].management_ipv4_address }}"
  register: vpc_data
  loop: "{{ MD.fabric.topology.vpc_peers }}"

- name: Check vPC Pair Status
  cisco.nac_dc_vxlan.dtc.vpc_pair_check:
    vpc_data: "{{ vpc_data }}"
```
