### ISSUE TITLE
Ingress replication is not allowed for border_gateway_spine

### ISSUE THREAD

**Issue by skaszlik** [netascode/ansible-dc-vxlan#405]
### Ansible Version

```shell
ansible [core 2.16.3]
Python 3.12.9
```

### Ansible Collection Versions

```shell
# ~/.pyenv/versions/sac-ndfc/lib/python3.10/site-packages/ansible/collections/ansible_collections
Collection         Version  
------------------ ---------
ansible.netcommon  7.1.0    
ansible.utils      5.1.2    

# nac-ndfc/collections/ansible_collections
Collection         Version  
------------------ ---------
ansible.posix      2.0.0    
cisco.dcnm         3.7.0    
cisco.nac_dc_vxlan 0.4.2-dev
community.general  10.1.0
```

### Cisco NDFC Version

```shell
12.2.2.241
```

### Cisco NX-OS Version

```shell
10.4.2.F
```

### Which role is this issue related to?

cisco.nac_dc_vxlan.validate

### Which section of the data model is this issue related to?

vxlan.global

### Expected Behavior

```shell
The validation process should detect these wrong settings and raise an error during TASK [cisco.nac_dc_vxlan.validate : Perform Required Syntax and Semantic Model Validation].
```

### Actual Behavior

```shell
When 'enable_ipv6_underlay' is enabled and 'replication_mode' is set to Ingress, the switch role cannot be set to border_gateway_spine. This causes an error with the message "VXLANv6 with ingress replication mode is not supported on border gateway switches."
```

### Ansible Playbook

```yaml
---
- hosts: nac-fabric1
  any_errors_fatal: true
  gather_facts: no
  ignore_errors: no

  roles:
    - role: cisco.nac_dc_vxlan.dtc.create
      tags: 'role_create'

    - role: cisco.nac_dc_vxlan.dtc.deploy
      tags: 'role_deploy'

    - role: cisco.nac_dc_vxlan.dtc.remove
      tags: 'role_remove'
```

### Steps to Reproduce

```shell
1. Set 'enable_ipv6_underlay' to True
2. Set 'replication_mode' to 'ingress'
3. Set switch role to 'border_gateway_spine'
```

### Relevant Debug Output

```shell
TASK [cisco.nac_dc_vxlan.deploy : Config-Save for Fabric nac-fabric1] *******************************************************************************
fatal: [nac-fabric1]: FAILED! => {"changed": false, "msg": {"DATA": "Invalid JSON response: Switch [VAC_SPINE21/99FYP2OV1NS]: Switch has role 'border gateway spine', VXLANv6 with ingress replication mode is not supported on border gateway switches ", "MESSAGE": "Internal Server Error", "METHOD": "POST", "REQUEST_PATH": "https://198.18.133.100:443/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/nac-fabric1/config-save", "RETURN_CODE": 500}}
```
