### ISSUE TITLE
Task "Manage Fabric <name> in NDFC" fails in case of IS-IS underlay in 0.4.2

### ISSUE THREAD

**Issue by marehler** [netascode/ansible-dc-vxlan#413]
### Ansible Version

```shell
ansible [core 2.16.3]
```

### Ansible Collection Versions

```shell
Collection                               Version
---------------------------------------- -------
ansible.netcommon                        7.1.0  
ansible.posix                            2.0.0  
ansible.utils                            5.1.2  
cisco.dcnm                               3.8.0  
cisco.nac_dc_vxlan                       0.4.2  
cisco.nxos                               9.4.0  
community.general                        10.1.0
```

### Cisco NDFC Version

```shell
12.2.3
```

### Cisco NX-OS Version

```shell
10.3(5)
```

### Which role is this issue related to?

cisco.nac_dc_vxlan.dtc.create

### Which section of the data model is this issue related to?

vxlan.underlay

### Expected Behavior

```shell
TASK [cisco.nac_dc_vxlan.create : Manage Fabric VXLAN-SITE2 in NDFC] ******************************************************************
changed: [marehler_vnd3_site2]
```

### Actual Behavior

```shell
TASK [cisco.nac_dc_vxlan.create : Manage Fabric VXLAN-SITE2 in NDFC] ******************************************************************
fatal: [marehler_vnd3_site2]: FAILED! => {"changed": false, "metadata": [{"action": "fabric_create", "check_mode": false, "sequence_number": 1, "state": "merged"}], "msg": "Module failed.", "response": [{"DATA": "Invalid JSON response: Error in validating provided name value pair: [ISIS_AREA_NUM]", "MESSAGE": "Internal Server Error", "METHOD": "POST", "REQUEST_PATH": "https://[2001:420:448b:8006::30]:443/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/VXLAN-SITE2/Easy_Fabric", "RETURN_CODE": 500, "sequence_number": 1}], "result": [{"changed": false, "sequence_number": 1, "success": false}]}
```

### Ansible Playbook

```yaml
---
# This is the main entry point playbook for calling the various roles in this collection.

- hosts: marehler_vnd3_site2
  any_errors_fatal: true
  gather_facts: no

  roles:
    # -----------------------
    # DataCenter Roles
    #   Role: cisco.netascode_dc_vxlan.dtc manages NDFC workflows
    #
    - role: cisco.nac_dc_vxlan.dtc.create
    - role: cisco.nac_dc_vxlan.dtc.deploy
    - role: cisco.nac_dc_vxlan.dtc.remove
```

### Steps to Reproduce

```shell
ansible-playbook -i inventory.yaml deploy.yaml
```

### Relevant Debug Output

```shell

```

### Root Cause Analysis

The IS-IS area number (net_area_number) is incorrectly handled as an integer. However it is a 4-byte hexadecimal value. This needs to be fixed in the schema as well as the defaults file. The issue has been introduced in release 0.4.2.

Proposed fix for schema file:
```
underlay_isis:
  net_area_number: regex('^[a-f0-9]{4}$', required=False)
```

Sample configuration data:
```
vxlan:
  underlay:
    isis:
      level: level-2
      network_point_to_point: true
      net_area_number: 000a
```
