### ISSUE TITLE
Task "Manage NDFC MSD Fabric Networks" fails for Update

### ISSUE THREAD

**Issue by marehler** [netascode/ansible-dc-vxlan#415]
### Ansible Version

```shell
ansible [core 2.16.3]
```

### Ansible Collection Versions

```shell
Collection                               Version
---------------------------------------- -------
ansible.netcommon                        7.1.0  
ansible.posix                            2.0.0  
ansible.utils                            5.1.2  
cisco.dcnm                               3.8.0  
cisco.nac_dc_vxlan                       0.4.2  
cisco.nxos                               9.4.0  
community.general                        10.1.0
```

### Cisco NDFC Version

```shell
12.2.3
```

### Cisco NX-OS Version

```shell
10.5(3)
```

### Which role is this issue related to?

cisco.nac_dc_vxlan.dtc.create

### Which section of the data model is this issue related to?

vxlan.multisite

### Expected Behavior

```shell
The task shall succeed, and if applicable networks shall be updated.
```

### Actual Behavior

```shell
The update, i.e. PUT operation fails. This occurs also if the config has not changed.

TASK [cisco.nac_dc_vxlan.create : Manage NDFC MSD Fabric Networks] ********************************************************************
fatal: [blndc01-cx-nd]: FAILED! => {"changed": false, "msg": {"DATA": {"Error": "Bad Request Error", "message": "Invalid Multicast Group Address (IPv4) ", "path": "/rest/top-down/fabrics/VXLAN_TRAINING/networks/USER02_50120", "status": "400", "timestamp": "2025-06-11 12:51:16.862"}, "MESSAGE": "Bad Request", "METHOD": "PUT", "REQUEST_PATH": "https://10.49.216.51:443/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/top-down/fabrics/VXLAN_TRAINING/networks/USER02_50120", "RETURN_CODE": 400}}
```

### Ansible Playbook

```yaml
---
# This is the main entry point playbook for calling the various roles in this collection.

- hosts: blndc01-cx-nd
  any_errors_fatal: true
  gather_facts: no

  roles:
    # -----------------------
    # DataCenter Roles
    #   Role: cisco.netascode_dc_vxlan.dtc manages NDFC workflows
    #
    - role: cisco.nac_dc_vxlan.dtc.create
    - role: cisco.nac_dc_vxlan.dtc.deploy
    - role: cisco.nac_dc_vxlan.dtc.remove
```

### Steps to Reproduce

```shell
* Run playbook
* Change config, e.g. gw_ip_address
* Run playbook again
* Or, run playbook again without config change but with "Diff run - false"
```

### Relevant Debug Output

```shell

```

**Comment by marehler** [comment]
The issue seems to be caused by the dcnm_network Ansible module. It can also be reproduced by running the following playbook twice. For the first run, the POST request succeeds, for the second run, the PUT request fails.

```
- name: Debug DCNM Networks
  hosts: blndc01-cx-nd
  any_errors_fatal: true
  gather_facts: no

  tasks:

  - name: Manage NDFC MSD Fabric Networks
    cisco.dcnm.dcnm_network:
      fabric: VXLAN_TRAINING
      state: replaced
      config:
      - net_name: USER02_50120
        vrf_name: USER02
        net_id: 50120
        vlan_id: 120
        gw_ip_subnet: '10.17.10.1/24'
        int_desc: 'Configured by Ansible NetAsCode'
        attach:
        - ip_address: 10.49.222.168
          ports: []
        - ip_address: 10.49.222.169
          ports: []
        deploy: false
```

Output:

```
ansible-playbook -i inventory.yaml playbooks/dcnm-networks.yaml 

PLAY [Debug DCNM Networks] **************************************************************************************************************************

TASK [Manage NDFC MSD Fabric Networks] **************************************************************************************************************
changed: [blndc01-cx-nd]

PLAY RECAP ******************************************************************************************************************************************
blndc01-cx-nd              : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

ansible-playbook -i inventory.yaml playbooks/dcnm-networks.yaml

PLAY [Debug DCNM Networks] **************************************************************************************************************************

TASK [Manage NDFC MSD Fabric Networks] **************************************************************************************************************
fatal: [blndc01-cx-nd]: FAILED! => {"changed": false, "msg": {"DATA": {"Error": "Bad Request Error", "message": "Invalid Multicast Group Address (IPv4) ", "path": "/rest/top-down/fabrics/VXLAN_TRAINING/networks/USER02_50120", "status": "400", "timestamp": "2025-06-11 14:44:17.871"}, "MESSAGE": "Bad Request", "METHOD": "PUT", "REQUEST_PATH": "https://10.49.216.51:443/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/top-down/fabrics/VXLAN_TRAINING/networks/USER02_50120", "RETURN_CODE": 400}}

NO MORE HOSTS LEFT **********************************************************************************************************************************

PLAY RECAP ******************************************************************************************************************************************
blndc01-cx-nd              : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```
