### ISSUE TITLE
VRF ID and Network ID Range is wrong

### ISSUE THREAD

**Issue by juarocha** [netascode/ansible-dc-vxlan#419]
### Ansible Version

```shell
ansible [core 2.16.3]
```

### Ansible Collection Versions

```shell
Collection         Version
------------------ -------
ansible.netcommon  7.1.0  
ansible.posix      2.0.0  
ansible.utils      5.1.2  
cisco.dcnm         3.8.0  
cisco.nac_dc_vxlan 0.4.2  
community.general  10.1.0
```

### Cisco NDFC Version

```shell
12.2.3
```

### Cisco NX-OS Version

```shell
NA
```

### Which role is this issue related to?

cisco.nac_dc_vxlan.dtc.create

### Which section of the data model is this issue related to?

vxlan.overlay

### Expected Behavior

```shell
VRF Id and network ID should be in the range 1-16777214
```

### Actual Behavior

```shell
Both Ids are in the range 1-1677215
```

### Ansible Playbook

```yaml
---
vxlan:
  overlay:
    vrfs:
      - name: NaC-VRF01
        vrf_id: 3210000
        vlan_id: 2001
    networks:
      - name: NaC-Net01
        vrf_name: NaC-VRF01
        net_id: 3240000
        vlan_id: 2301

```

### Steps to Reproduce

```shell
Run the collection with the provided IDs
```

### Relevant Debug Output

```shell
Schema error:
Value is above the maximum of 1677215.
```
