### ISSUE TITLE
Playbook failed for RP_COUNT=4 and rp_mode=bidir and rp_loopbacks set

### ISSUE THREAD

**Issue by skaszlik** [netascode/ansible-dc-vxlan#425]
### Ansible Version

```shell
ansible [core 2.16.3]
  python version = 3.10.14
  jinja version = 3.1.6
```

### Ansible Collection Versions

```shell
Collection         Version  
------------------ ---------
ansible.netcommon  7.1.0    
ansible.posix      2.0.0    
ansible.utils      5.1.2    
cisco.dcnm         3.8.0    
cisco.nac_dc_vxlan 0.4.2-dev
community.general  10.1.0
```

### Cisco NDFC Version

```shell
"version": "12.2.2.241"
```

### Cisco NX-OS Version

```shell
--
```

### Which role is this issue related to?

other

### Which section of the data model is this issue related to?

vxlan.fabric

### Expected Behavior

```shell
The below configuration should be allowed to deploy


Config file


---
vxlan:
  fabric:
    name: nac-fabric1
    type: VXLAN_EVPN
  global:
    bgp_asn: "65011"
    route_reflectors: 4
    anycast_gateway_mac: 12:34:56:78:90:00
  underlay:
    general:
      routing_protocol: ospf
      enable_ipv6_underlay: false
      replication_mode: multicast
    multicast:
      rendezvous_points: 4
      rp_mode: bidir
      underlay_rp_loopback_id: 254
      underlay_primary_rp_loopback_id: 2
      underlay_backup_rp_loopback_id: 3
      underlay_second_backup_rp_loopback_id: 4
      underlay_third_backup_rp_loopback_id: 5
```

### Actual Behavior

```shell
The deploy failed with error:


"msg": "The following parameter(value) combination(s) are invalid and need to be reviewed: Fabric: nac-fabric1, PHANTOM_RP_LB_ID3(4) requires RP_COUNT == 4, RP_COUNT valid values: [2, 4]. PHANTOM_RP_LB_ID4(5) requires RP_COUNT == 4, RP_COUNT valid values: [2, 4]. ",
```

### Ansible Playbook

```yaml
I tried both NAC and custom playbook with cisco.dcnm.dcnm_fabric collection. The behavior is the same which means the issue is within the dcnm collection.

The custom playbook:

---
- hosts: nac-fabric1
  any_errors_fatal: true
  # gather_facts: no
  collections:
    - cisco.dcnm

  vars:
    fabric_name: "nac-fabric1"  
    switch_ip: "198.18.133.14"

  tasks:
    - name: Update fabrics (nac test)
      cisco.dcnm.dcnm_fabric:
        state: merged
        config:
        - FABRIC_NAME: nac-fabric1
          FABRIC_TYPE: VXLAN_EVPN
          DEPLOY: False

          BGP_AS: "65011"
          UNDERLAY_IS_V6: False
          FABRIC_INTERFACE_TYPE: p2p
          SUBNET_TARGET_MASK: 30
          LINK_STATE_ROUTING: ospf
          RR_COUNT: 4
          ANYCAST_GW_MAC: 12:34:56:78:90:00

          REPLICATION_MODE: Multicast
          RP_COUNT: 4
          RP_MODE: bidir
          RP_LB_ID: 254
          ENABLE_TRM: False
          MULTICAST_GROUP_SUBNET: 239.1.1.0/25
          PHANTOM_RP_LB_ID1: 2
          PHANTOM_RP_LB_ID2: 3
          PHANTOM_RP_LB_ID3: 4
          PHANTOM_RP_LB_ID4: 5
```

### Steps to Reproduce

```shell
Use the provided ansible playbook and cisco.dcnm collection 3.8.0
```

### Relevant Debug Output

```shell
TASK [cisco.nac_dc_vxlan.create : Manage Fabric nac-fabric1 in NDFC] ******************************************************************************************************
fatal: [nac-fabric1]: FAILED! => {"changed": false, "msg": "The following parameter(value) combination(s) are invalid and need to be reviewed: Fabric: nac-fabric1, PHANTOM_RP_LB_ID3(4) requires RP_COUNT == 4, RP_COUNT valid values: [2, 4]. PHANTOM_RP_LB_ID4(5) requires RP_COUNT == 4, RP_COUNT valid values: [2, 4]. ", "response": [{}], "result": [{}]}
```
