### ISSUE TITLE
Role: cisco.nac_dc_vxlan.dtc.create - Interface Access

### ISSUE THREAD

**Issue by mikewiebe** [netascode/ansible-dc-vxlan#7]
Role Entry Point: https://github.com/netascode/ansible-dc-vxlan/blob/main/roles/dtc/create/tasks/ndfc/main.yml#L31

This task captures the work items needed to enable configuration and deployment of access interfaces.

* Add a new file called `int_access.yml` under `https://github.com/netascode/ansible-dc-vxlan/tree/main/roles/dtc/common/tasks` directory.
* Add entry under `cisco.nac_dc_vxlan.dtc.common` role to include task file for access interfaces.
  * https://github.com/netascode/ansible-dc-vxlan/blob/main/roles/dtc/common/tasks/main.yml
* Add tasks inside of `int_access.yml`  to create jinja2 template defining payload for list of access interfaces to be configured on the device.

**Jinja2 Template Contents**

This template generates the payload used by the `cisco.dcnm.dcnm_interface` module to configure/manage access interfaces.

Module: https://github.com/CiscoDevNet/ansible-dcnm/blob/main/docs/cisco.dcnm.dcnm_interface_module.rst

```yaml
---
# This NDFC loopback interface data is auto-generated
# DO NOT EDIT MANUALLY
#
{% for switch in MD.fabric.topology.switches %}
{% for interface in switch.interfaces %}
- name: {{ interface.name }}
  type: eth
  switch:
    - {{ switch.management.management_ipv4_address}}
  deploy: false
  profile:
    description: {{ interface.description | default(omit) }}
    admin_state: {{ interface.enabled | default(omit) }}
    mode: access
    ipv4_addr: {{ interface.ipv4_address | default(omit) }}

{% endfor %}
{% endfor %}
```

**Sample Module Call For Access Interface:**

```yaml
    - name: Create ethernet interfaces
      cisco.dcnm.dcnm_interface: &eth_merge
        check_deploy: True
        fabric: "{{ ansible_it_fabric }}" 
        state: replaced                         # only choose form [merged, replaced, deleted, overridden, query]
          - name: "{{ ansible_eth_intf8 }}"   # should be of the form eth<port-id>
            type: eth                         # choose from this list [pc, vpc, sub_int, lo, eth, svi]
            switch:
              - "{{ ansible_switch1 }}"       # provide the switch information where the config is to be deployed
            deploy: true                      # choose from [true, false]
            profile:
              admin_state: true               # choose from [true, false]
              mode: access                    # choose from [trunk, access, routed, monitor, epl_routed]
              speed: 'Auto'                   # choose from ['Auto', '100Mb', '1Gb', '10Gb', '25Gb', '40Gb', '100Gb' ]
              bpdu_guard: true                # choose from [true, false, 'no']
              port_type_fast: true            # choose from [true, false]
              mtu: default                    # choose from [default, jumbo]
              access_vlan: 31                 # 
              cmds:                           # Freeform config
                - no shutdown
              description: "eth interface acting as access"
```
