### ISSUE TITLE
Use dcnm_link to prepare interfaces for vpc peering

### ISSUE THREAD

**Issue by mikewiebe** [netascode/ansible-dc-vxlan#80]
I would prefer we use the interface module `query` state to get the status of these interfaces and loop until it reaches the desired state.

Here is an example using the network module (of course use the dcnm_interface module instead)

https://github.com/CiscoDevNet/ansible-dcnm/blob/develop/tests/integration/targets/dcnm_network/tests/dcnm/replaced.yaml#L58

```yaml
- name: Query Interface State
  cisco.dcnm.dcnm_interface:
    fabric: "{{ test_fabric }}"
    state: query
    config:
      - name: "{{ ansible_eth_intf2 }}"
         switch:
            - "{{ ansible_switch1 }}" 
  register: query_result
  until:
    - "query_result.response[0] .... Some condition here.... "
    - "query_result.response[1] .... Some condition here ..."
  retries: 30
  delay: 2
```

_Originally posted by @mikewiebe in https://github.com/netascode/ansible-dc-vxlan/pull/74#discussion_r1578039887_
