### ISSUE TITLE
Fix | admin state to use variable in ndfc_interface_vpc.j2

### ISSUE THREAD

**Issue by rrahimm** [netascode/ansible-dc-vxlan#86]
Currently, the admin_state parameter in the Jinja Template is not using the enabled variable. Its a minor fix. Creating this for tracking and closing it.

```
  deploy: false
  profile:
    admin_state: {{ true | default(defaults.fabric.topology.switches.interfaces.topology_switch_trunk_po_interface.enabled) }}
    mode: {{ switches[peer1].mode }}
```
